{{- if .Values.sealedSecret.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.name | default (include "my-app.fullname" .) }}
  {{- with .Values.sealedSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- toYaml .Values.sealedSecret.encryptedData | nindent 4 }}
  template:
    metadata:
      name: {{ .Values.sealedSecret.name | default (include "my-app.fullname" .) }}
      labels:
        {{- include "my-app.labels" . | nindent 8 }}
{{- end }}
