apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  # Prometheus Rules
  - rules/prometheus-rules.yaml
  
  # Grafana Dashboards
  - dashboards/cluster-overview-dashboard.yaml
  - dashboards/node-details-dashboard.yaml
  - dashboards/oom-killer-dashboard.yaml
  - dashboards/network-traffic-dashboard.yaml
  - dashboards/pod-monitoring-dashboard.yaml
  - dashboards/storage-dashboard.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: monitoring-config
      app.kubernetes.io/managed-by: kustomize
