apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: traefik-dashboard
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "traefik.vagrant.local"
      - op: replace
        path: /spec/rules/0/host
        value: "traefik.vagrant.local"
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: "ca-issuer"
