apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
spec:
  instances: {{ .Values.cluster.instances }}
  
  # Example of bootstrap method
  bootstrap:
    initdb:
      database: {{ .Values.cluster.bootstrap.initdb.database }}
      owner: {{ .Values.cluster.bootstrap.initdb.owner }}
      secret:
        name: {{ .Values.cluster.bootstrap.initdb.secret.name }}

  storage:
    size: {{ .Values.cluster.storage.size }}
