# =============================================================================
# Grafana Ingress - Vagrant Overlay
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: grafana.vagrant.local
      - op: replace
        path: /spec/rules/0/host
        value: grafana.vagrant.local
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging
    target:
      kind: Ingress
      name: grafana
