apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-app

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: example-app
  app.kubernetes.io/part-of: applications
  app.kubernetes.io/managed-by: argocd
