# =============================================================================
# Grafana Ingress - Production Overlay
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: grafana.raspi.local
      - op: replace
        path: /spec/rules/0/host
        value: grafana.raspi.local
    target:
      kind: Ingress
      name: grafana
