apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

bases:
  - ../../base

patches:
  - target:
      kind: IPAddressPool
      name: default-pool
    patch: |-
      - op: replace
        path: /spec/addresses/0
        value: 192.168.56.200-192.168.56.220
